# Generated by Django 4.1 on 2022-08-17 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood_by', models.BooleanField(default=False)),
                ('neighborhood', models.CharField(blank=True, max_length=111)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111)),
            ],
        ),
        migrations.CreateModel(
            name='TreeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111)),
            ],
        ),
        migrations.CreateModel(
            name='TreeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111)),
            ],
        ),
        migrations.CreateModel(
            name='TreePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('tree_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.treename')),
            ],
        ),
        migrations.AddField(
            model_name='treename',
            name='tree_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.treetype'),
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_number', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('tree_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.treename')),
                ('tree_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.treetype')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.district'),
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region'),
        ),
    ]
