# Generated by Django 4.1 on 2022-08-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboard',
            old_name='overall_tree',
            new_name='number_of_donors',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='planted_tree',
            new_name='planted_trees',
        ),
    ]
